k8s_minor: "v1.31"
k8s_pkg_version: "1.31.0-1.1"

k8s_repo_list: "/etc/apt/sources.list.d/kubernetes-stable-{{ k8s_minor }}.list"
k8s_keyring: "/etc/apt/keyrings/kubernetes-apt-keyring.gpg"
old_repo_list: "/etc/apt/sources.list.d/kubernetes.list"
